#! /usr/bin/env ruby

require_relative '../lib/project_creator'

# ProjectCreator.parse(ARGV)
project_name = ARGV.shift
if project_name == nil
  puts "Please specify a project name!"
  exit(false)
end
options = ProjectCreator.parse(ARGV)
creator = ProjectCreator.new(project_name, options)
# creator = ProjectCreator.parse
creator.build_file_structure
